language: node_js
node_js:
   - "0.10"
before_install: npm install -g grunt-cli
install: npm install
script: grunt build
branches:
   only: master
cache:
   directories:
      - node_modules
after_success:
   "curl --ftp-create-dirs -T public -u $FTP_USER:$FTP_PASSWORD ftp://${FTP_HOST}/${FTP_PATH}"
notifications:
   email:
      on_success: change
      on_failure: always