language: node_js
addons:
  apt:
    packages:
      - lftp
branches:
  only:
     - master
node_js:
  - "stable"
before_install:
  - lftp -e "set ftp:list-options -a; rm -r ${FTP_PATH}; bye" -u $FTP_USER,$FTP_PASSWORD $FTP_HOST
install:
  - rvm install 2.2.2
  - gem install jekyll
  - gem install octopress-autoprefixer
  - gem install jekyll-paginate
  - npm install
script:
  - npm run prod
after_success:
  - lftp -e "mirror -R ${PROJECT_PATH} ${FTP_PATH}; mv ${FTP_PATH}/robots-pre.txt ${FTP_PATH}/robots.txt; mv ${FTP_PATH}/.htaccess-pre ${FTP_PATH}/.htaccess; bye" -u $FTP_USER,$FTP_PASSWORD $FTP_HOST